name: calculadora
description: Projeto pos IFBA

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  rxdart: ^0.27.0
  bloc_pattern: ^3.0.0
  flutter:
    sdk: flutter


  # dependencies external

  #charts
  syncfusion_flutter_gauges:

  #open URLs
  url_launcher: ^6.0.3  

dev_dependencies:
  mockito: ^5.0.7
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
